development:
  adapter: mysql2
  database: DKSSOQ_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: DKSSOQ_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: DKSSOQ_production
  username: root
  password: 
  encoding: utf8
