# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20130226212258) do

  create_table "proposals", :force => true do |t|
    t.string   "name"
    t.string   "anum"
    t.string   "final"
    t.datetime "date"
    t.string   "time"
    t.integer  "propoasal_manager"
    t.integer  "coordinator"
    t.integer  "reviewer"
    t.datetime "coord_meeting_datetime"
    t.float    "fee_total"
    t.float    "fee_dks"
    t.integer  "prime_sub"
    t.integer  "type_doc"
    t.integer  "client_copies"
    t.integer  "dks_staff_copies"
    t.integer  "subconsultants_copies"
    t.integer  "filing_copies"
    t.integer  "delivery_by"
    t.boolean  "prod_page_limit"
    t.boolean  "prod_single_sided"
    t.boolean  "prod_divider_tabs"
    t.boolean  "prod_graphics"
    t.boolean  "prod_other_int"
    t.string   "prod_other"
    t.string   "prod_no"
    t.boolean  "prod_double_sided"
    t.string   "prod_no2"
    t.integer  "prod_subtabs"
    t.boolean  "prod_cover"
    t.boolean  "prod_schedule"
    t.boolean  "prod_org_chart"
    t.string   "prod_special_instructions"
    t.string   "delv_trans_name"
    t.string   "delv_trans_address"
    t.string   "delv_trans_attention"
    t.string   "delv_deliver_name"
    t.string   "delv_deliver_address"
    t.string   "delv_deliver_attention"
    t.integer  "mand_subconsultant_resp"
    t.datetime "mand_subconsultant_datetime"
    t.integer  "mand_subconsultant_reviewer"
    t.integer  "mand_draft_resp"
    t.datetime "mand_draft_datetime"
    t.integer  "mand_draft_reviewer"
    t.integer  "mand_sub_final_edits_resp"
    t.datetime "mand_sub_final_edits_datetime"
    t.integer  "mand_sub_final_edits_reviewer"
    t.integer  "mand_cam_ready_resp"
    t.datetime "mand_cam_ready_datetime"
    t.integer  "mand_cam_ready_reviewer"
    t.integer  "mand_final_check_resp"
    t.datetime "mand_final_check_datetime"
    t.integer  "mand_final_check_reviewer"
    t.integer  "mand_print_bind_resp"
    t.datetime "mand_print_bind_datetime"
    t.integer  "mand_print_bind_reviewer"
    t.integer  "mand_out_door_deadline_resp"
    t.datetime "mand_out_door_deadline_datetime"
    t.integer  "mand_out_door_deadline_reviewer"
    t.string   "dead_cov_sec"
    t.integer  "dead_cov_resp"
    t.datetime "dead_cov_dd"
    t.integer  "dead_cov_fd"
    t.boolean  "dead_cov_rev"
    t.boolean  "dead_cov_na"
    t.datetime "dead_cov_done"
    t.string   "dead_stand_sec"
    t.integer  "dead_stand_resp"
    t.datetime "dead_stand_dd"
    t.datetime "dead_stand_fd"
    t.integer  "dead_stand_rev"
    t.boolean  "dead_stand_na"
    t.boolean  "dead_stand_done"
    t.string   "dead_firm_sec"
    t.integer  "dead_firm_resp"
    t.datetime "dead_firm_dd"
    t.datetime "dead_firm_fd"
    t.integer  "dead_firm_rev"
    t.boolean  "dead_firm_na"
    t.boolean  "dead_firm_done"
    t.string   "dead_lang_sec"
    t.integer  "dead_lang_resp"
    t.datetime "dead_lang_dd"
    t.datetime "dead_lang_fc"
    t.integer  "dead_lang_rev"
    t.boolean  "dead_lang_na"
    t.boolean  "dead_lang_done"
    t.string   "dead_capsule_sec"
    t.integer  "dead_capsule_resp"
    t.datetime "dead_capsule_dd"
    t.datetime "dead_capsule_fd"
    t.integer  "dead_capsule_rev"
    t.boolean  "dead_capsule_na"
    t.boolean  "dead_capsule_done"
    t.string   "dead_full_res_sec"
    t.integer  "dead_full_res_resp"
    t.datetime "dead_full_res_dd"
    t.datetime "dead_full_res_fd"
    t.integer  "dead_full_res_rev"
    t.boolean  "dead_full_res_na"
    t.boolean  "dead_full_res_done"
    t.string   "dead_graph_cover_sec"
    t.integer  "dead_graph_cover_resp"
    t.datetime "dead_graph_cover_dd"
    t.datetime "dead_graph_cover_fd"
    t.integer  "dead_graph_cover_rev"
    t.boolean  "dead_graph_cover_na"
    t.boolean  "dead_graph_cover_done"
    t.string   "dead_graph_org_sec"
    t.integer  "dead_graph_org_resp"
    t.datetime "dead_graph_org_dd"
    t.datetime "dead_graph_org_fc"
    t.integer  "dead_graph_org_rev"
    t.boolean  "dead_graph_org_na"
    t.boolean  "dead_graph_org_done"
    t.string   "dead_graph_sch_sec"
    t.integer  "dead_graph_sch_resp"
    t.datetime "dead_graph_sch_dd"
    t.datetime "dead_graph_sch_fc"
    t.integer  "dead_graph_sch_rev"
    t.boolean  "dead_graph_sch_na"
    t.boolean  "dead_graph_sch_done"
    t.string   "dead_graphics_sec"
    t.integer  "dead_graphics_resp"
    t.datetime "dead_graphics_dd"
    t.datetime "dead_graphics_fc"
    t.integer  "dead_graphics_rev"
    t.boolean  "dead_graphics_na"
    t.boolean  "dead_graphics_done"
    t.string   "dead_text_work_scope_sec"
    t.integer  "dead_text_work_scope_resp"
    t.datetime "dead_text_work_scope_dd"
    t.datetime "dead_text_work_scope_fd"
    t.integer  "dead_text_work_scope_rev"
    t.boolean  "dead_text_work_scope_na"
    t.boolean  "dead_text_work_scope_done"
    t.string   "dead_text_qual_sec"
    t.integer  "dead_text_qual_resp"
    t.datetime "dead_text_qual_dd"
    t.datetime "dead_text_qual_fd"
    t.integer  "dead_text_qual_rev"
    t.boolean  "dead_text_qual_na"
    t.boolean  "dead_text_qual_done"
    t.string   "dead_text_res_sec"
    t.integer  "dead_text_res_resp"
    t.datetime "dead_text_res_dd"
    t.datetime "dead_text_res_fd"
    t.integer  "dead_text_res_rev"
    t.boolean  "dead_text_res_na"
    t.boolean  "dead_text_res_done"
    t.string   "dead_text_short_sec"
    t.integer  "dead_text_short_resp"
    t.datetime "dead_text_short_dd"
    t.datetime "dead_text_short_fd"
    t.integer  "dead_text_short_rev"
    t.boolean  "dead_text_short_na"
    t.boolean  "dead_text_short_done"
    t.string   "dead_text_und_sec"
    t.integer  "dead_text_und_resp"
    t.datetime "dead_text_und_dd"
    t.datetime "dead_text_und_fd"
    t.integer  "dead_text_und_rev"
    t.boolean  "dead_text_und_na"
    t.boolean  "dead_text_und_done"
    t.string   "dead_text_sec"
    t.integer  "dead_text_resp"
    t.datetime "dead_text_dd"
    t.datetime "dead_text_fd"
    t.integer  "dead_text_rev"
    t.boolean  "dead_text_na"
    t.boolean  "dead_text_done"
    t.string   "dead_div_tabs_sec"
    t.integer  "dead_div_tabs_resp"
    t.datetime "dead_div_tabs_dd"
    t.datetime "dead_div_tabs_fd"
    t.integer  "dead_div_tabs_rev"
    t.boolean  "dead_div_tabs_na"
    t.boolean  "dead_div_tabs_done"
    t.string   "dead_spec_form_sec"
    t.integer  "dead_spec_form_resp"
    t.datetime "dead_spec_form_dd"
    t.datetime "dead_spec_form_fd"
    t.integer  "dead_spec_form_rev"
    t.boolean  "dead_spec_form_na"
    t.boolean  "dead_spec_form_done"
    t.string   "dead_bud_est_sec"
    t.integer  "dead_bud_est_resp"
    t.datetime "dead_bud_est_dd"
    t.datetime "dead_bud_est_fd"
    t.integer  "dead_bud_est_rev"
    t.boolean  "dead_bud_est_na"
    t.boolean  "dead_bud_est_done"
    t.string   "dead_cont_rev_sec"
    t.integer  "dead_cont_rev_resp"
    t.datetime "dead_cont_rev_dd"
    t.datetime "dead_cont_rev_fd"
    t.integer  "dead_cont_rev_rev"
    t.boolean  "dead_cont_rev_na"
    t.boolean  "dead_cont_rev_done"
    t.string   "dead_work_ex_sec"
    t.integer  "dead_work_ex_resp"
    t.datetime "dead_work_ex_dd"
    t.datetime "dead_work_ex_fd"
    t.integer  "dead_work_ex_rev"
    t.boolean  "dead_work_ex_na"
    t.boolean  "dead_work_ex_done"
    t.boolean  "attachments_customized_outline"
    t.boolean  "attachments_subconsultant_details"
    t.integer  "item_needed_dead_resume_num"
    t.boolean  "item_needed_dead_resume_due_date"
    t.integer  "item_needed_dead_resume_req_sub_num"
    t.boolean  "item_needed_dead_short_bio_due_date"
    t.integer  "item_needed_dead_short_bio_req_sub_num"
    t.boolean  "item_needed_dead_firm_profile_due_date"
    t.integer  "item_needed_dead_firm_profile_req_sub_num"
    t.boolean  "item_needed_dead_quals_due_date"
    t.integer  "item_needed_dead_quals_req_sub_num"
    t.boolean  "item_needed_dead_task_desc_due_date"
    t.integer  "item_needed_dead_task_desc_req_sub_num"
    t.boolean  "item_needed_dead_bud_est_due_date"
    t.integer  "item_needed_dead_bud_est_req_sub_num"
    t.datetime "created_at",                                :null => false
    t.datetime "updated_at",                                :null => false
  end

  create_table "subconsultants", :force => true do |t|
    t.string   "firm_name"
    t.string   "contact_name"
    t.text     "contact_address"
    t.string   "contact_phone"
    t.string   "contact_fax"
    t.string   "contact_email"
    t.datetime "created_at",      :null => false
    t.datetime "updated_at",      :null => false
    t.integer  "proposal_id"
    t.integer  "sub_num"
  end

  create_table "users", :force => true do |t|
    t.string   "email"
    t.string   "first_name"
    t.string   "last_name"
    t.string   "password_hash"
    t.string   "password_salt"
    t.boolean  "admin"
    t.datetime "created_at",    :null => false
    t.datetime "updated_at",    :null => false
  end

end
